# Generated by Django 4.2.7 on 2025-08-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_favorite_ad_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_things', through='ads.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
